default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: strv_addressbook_development

test:
  <<: *default
  database: strv_addressbook_test

production:
  <<: *default
  database: strv_addressbook_production
  username: strv_addressbook
  password: <%= ENV['STRV_ADDRESSBOOK_DATABASE_PASSWORD'] %>
